### ISSUE TITLE
panel info photos

### ISSUE THREAD

**Issue by DemonRem** [JonathanOrr/A321Neo-FXPL#42]
@JonathanOrr 

something i really like and i would like to add new photos 
is that info on the panel where are those photo located?
![panel](https://user-images.githubusercontent.com/29927382/110495300-0db55180-80fd-11eb-911b-28552ca82f2f.png)

**Comment by hkkhkhkhk** [comment]
Please.. That page is reserved for the user manual and I put random images on (from Animes I watched). 
Please try not to open issues on Github again, as we would like to keep the repository clean.
