### ISSUE TITLE
FPS issue

### ISSUE THREAD

**Issue by 150song** [JonathanOrr/A321Neo-FXPL#44]
I get only 6fps in cockpit, and 10fps looking at the aircraft.
60fps when not looking the aircraft.
On MacOS

**Comment by arnav7633** [comment]
> I get only 6fps in cockpit, and 10fps looking at the aircraft.
> 60fps when not looking the aircraft.
> On MacOS

Can u tell un a base line with the default 737 or the zibo 737

**Comment by rico23rico** [comment]
Please use the Discord channels to report performance issues and discuss about this. Moreover, we improved many things since April, VRAM exhaustion may have been the problem.
