### ISSUE TITLE
Livery on A321 not working

### ISSUE THREAD

**Issue by Jun3-dev** [JonathanOrr/A321Neo-FXPL#62]
Please do not report bugs / missing functionalities at this stage of the development.

Follow our Discord server: https://discord.gg/ByeyTXS
When Loading any livery on this aircraft, instead of an actual livery it just displays this;
![image](https://user-images.githubusercontent.com/82641992/133357594-0340253a-2051-4a8a-8ddb-f522e37f4249.png)
![image](https://user-images.githubusercontent.com/82641992/133357609-7519481a-8d18-430f-9884-47e9587e3677.png)

**Comment by todirbg** [comment]
`NOTE: The model is being redone: the external texture has been temporarily removed`
Thats what the readme says.

**Comment by Jun3-dev** [comment]
sorry
