### ISSUE TITLE
Missing scenery

### ISSUE THREAD

**Issue by ericrange** [JonathanOrr/A321Neo-FXPL#73]
i cloned the repo in the aircraft directory as described

![Unbenannt](https://user-images.githubusercontent.com/1785416/148675380-0e6eff2e-e046-4f9c-948c-124ffbab004f.jpg)

**Comment by saucec0de** [comment]
Hi. I guess that by "missing scenery" you mean "missing livery".
Have you read the big fat warning on the main page, under the section "Current Visual state"?
